const robot = require('robotjs');

// Data array yang akan dikirim
const messages = [
  'Hidup adalah perjalanan, bukan tujuan.',
  'Kesuksesan dimulai dari langkah kecil.',
  'Jangan takut gagal, takutlah tidak mencoba.',
  'Kebahagiaan ada dalam diri sendiri.',
  'Setiap masalah adalah pelajaran berharga.',
  'Jadilah perubahan yang ingin kamu lihat di dunia.',
  'Kesabaran adalah kunci kesuksesan.',
  'Mimpi besar, mulai dari langkah kecil.',
  'Jangan menunggu kesempatan, ciptakanlah.',
  'Kegagalan adalah batu loncatan menuju kesuksesan.',
  'Hidup ini singkat, manfaatkan setiap detiknya.',
  'Jangan bandingkan dirimu dengan orang lain.',
  'Kebaikan akan kembali kepada yang melakukannya.',
  'Belajar dari kesalahan adalah tanda kebijaksanaan.',
  'Jangan menyerah, hari esok bisa jadi lebih baik.',
  'gas kata-kata lagi bg?',
  'Kesederhanaan adalah kunci kebahagiaan.',
  'Jadilah diri sendiri, itu yang terbaik.',
  'Kesuksesan adalah hasil dari kerja keras.',
  'Jangan takut bermimpi, takutlah tidak bertindak.',
  'Hidup adalah tentang memberi, bukan menerima.',
  'Setiap hari adalah kesempatan baru.',
  'Jangan biarkan ketakutan menghentikanmu.',
  'Kebahagiaan adalah pilihan, bukan takdir.',
  'Jadilah cahaya dalam kegelapan.',
  'Kesuksesan adalah perjalanan, bukan tujuan.',
  'Jangan menunggu waktu yang tepat, mulailah sekarang.',
  'Hidup ini terlalu singkat untuk menyesal.',
  'Jangan biarkan masa lalu mengendalikanmu.',
  'Kebaikan kecil bisa membuat perbedaan besar.',
  'Capek negbadut uii',
  'Jadilah pribadi yang selalu bersyukur.',
  'Kesuksesan datang dari ketekunan.',
  'Jangan takut mengambil risiko.',
  'Hidup adalah tentang belajar dan tumbuh.',
  'Jangan biarkan kegagalan menghentikanmu.',
  'Kebahagiaan ada dalam hal-hal kecil.',
  'Jadilah pribadi yang penuh kasih sayang.',
  'Kesuksesan adalah hasil dari konsistensi.',
  'Jangan menunggu sempurna, mulailah sekarang.',
  'Hidup adalah tentang memberi makna.',
  'Jangan biarkan orang lain mendefinisikanmu.',
  'Kebaikan adalah bahasa universal.',
  'Jadilah pribadi yang selalu optimis.',
  'Kesuksesan adalah tentang proses, bukan hasil.',
  'Sampai kapan gini terus bg',
  'Jangan takut bermimpi besar.',
  'Hidup adalah tentang menciptakan kenangan.',
  'Jangan biarkan rasa takut mengendalikanmu.',
  'Kebahagiaan adalah ketika kita bersyukur.',
  'Jadilah pribadi yang selalu rendah hati.',
  'Kesuksesan adalah tentang ketekunan.',
  'Jangan menunggu kesempatan, ciptakanlah.',
  'Hidup adalah tentang memberi, bukan menerima.',
  'Jangan biarkan kegagalan menghentikanmu.',
  'Kebahagiaan ada dalam hal-hal kecil.',
  'Jadilah pribadi yang penuh kasih sayang.',
  'Kesuksesan adalah hasil dari konsistensi.',
  'Jangan menunggu sempurna, mulailah sekarang.',
  'Hidup adalah tentang memberi makna.',
  'Wenn bang',
  'Jangan biarkan orang lain mendefinisikanmu.',
  'Kebaikan adalah bahasa universal.',
  'Jadilah pribadi yang selalu optimis.',
  'Kesuksesan adalah tentang proses, bukan hasil.',
  'Jangan takut bermimpi besar.',
  'Hidup adalah tentang menciptakan kenangan.',
  'Jangan biarkan rasa takut mengendalikanmu.',
  'Kebahagiaan adalah ketika kita bersyukur.',
  'Jadilah pribadi yang selalu rendah hati.',
  'Kesuksesan adalah tentang ketekunan.',
  'Jangan menunggu kesempatan, ciptakanlah.',
  'Hidup adalah tentang memberi, bukan menerima.',
  'Jangan biarkan kegagalan menghentikanmu.',
  'Kebahagiaan ada dalam hal-hal kecil.',
  'Gas kata-kata lagi?',
  'Jadilah pribadi yang penuh kasih sayang.',
  'Kesuksesan adalah hasil dari konsistensi.',
  'Jangan menunggu sempurna, mulailah sekarang.',
  'Hidup adalah tentang memberi makna.',
  'Jangan biarkan orang lain mendefinisikanmu.',
  'Kebaikan adalah bahasa universal.',
  'Jadilah pribadi yang selalu optimis.',
  'Kesuksesan adalah tentang proses, bukan hasil.',
  'Jangan takut bermimpi besar.',
  'Hidup adalah tentang menciptakan kenangan.',
  'Jangan biarkan rasa takut mengendalikanmu.',
  'Kebahagiaan adalah ketika kita bersyukur.',
  'Jadilah pribadi yang selalu rendah hati.',
  'Kesuksesan adalah tentang ketekunan.',
  'Hari-hari ngebadut wokwokwok',
  'Jangan menunggu kesempatan, ciptakanlah.',
  'Hidup adalah tentang memberi, bukan menerima.',
  'Jangan biarkan kegagalan menghentikanmu.',
  'Kebahagiaan ada dalam hal-hal kecil.',
  'Jadilah pribadi yang penuh kasih sayang.',
  'Kesuksesan adalah hasil dari konsistensi.',
  'Jangan menunggu sempurna, mulailah sekarang.',
  'Hidup adalah tentang memberi makna.',
  'Jangan biarkan orang lain mendefinisikanmu.',
  'Kebaikan adalah bahasa universal.',
  'Jadilah pribadi yang selalu optimis.',
  'Kesuksesan adalah tentang proses, bukan hasil.',
  'Jangan takut bermimpi besar.',
  'Hidup adalah tentang menciptakan kenangan.',
  'Capek juga uii',
  'Jangan biarkan rasa takut mengendalikanmu.',
  'Kebahagiaan adalah ketika kita bersyukur.',
  'Jadilah pribadi yang selalu rendah hati.',
  'Kesuksesan adalah tentang ketekunan.',
  'Jangan menunggu kesempatan, ciptakanlah.',
  'Hidup adalah tentang memberi, bukan menerima.',
  'Jangan biarkan kegagalan menghentikanmu.',
  'Kebahagiaan ada dalam hal-hal kecil.',
  'Jadilah pribadi yang penuh kasih sayang.',
  'Kesuksesan adalah hasil dari konsistensi.',
  'Jangan menunggu sempurna, mulailah sekarang.',
  'Hidup adalah tentang memberi makna.',
  'Jangan biarkan orang lain mendefinisikanmu.',
  'Kebaikan adalah bahasa universal.',
  'Gas lagi lah',
  'Jadilah pribadi yang selalu optimis.',
  'Kesuksesan adalah tentang proses, bukan hasil.',
  'Jangan takut bermimpi besar.',
  'Hidup adalah tentang menciptakan kenangan.',
  'Jangan biarkan rasa takut mengendalikanmu.',
  'Kebahagiaan adalah ketika kita bersyukur.',
  'Jadilah pribadi yang selalu rendah hati.',
  'Kesuksesan adalah tentang ketekunan.',
  'Jangan menunggu kesempatan, ciptakanlah.',
  'Hidup adalah tentang memberi, bukan menerima.',
  'Jangan biarkan kegagalan menghentikanmu.',
  'Kebahagiaan ada dalam hal-hal kecil.',
  'Jadilah pribadi yang penuh kasih sayang.',
  'Kesuksesan adalah hasil dari konsistensi.',
  'ahhh sudah',
  'Jangan menunggu sempurna, mulailah sekarang.',
  'Hidup adalah tentang memberi makna.',
  'Jangan biarkan orang lain mendefinisikanmu.',
  'Kebaikan adalah bahasa universal.',
  'Jadilah pribadi yang selalu optimis.',
  'Kesuksesan adalah tentang proses, bukan hasil.',
  'Jangan takut bermimpi besar.',
  'Hidup adalah tentang menciptakan kenangan.',
  'Jangan biarkan rasa takut mengendalikanmu.',
  'Kebahagiaan adalah ketika kita bersyukur.',
  'Jadilah pribadi yang selalu rendah hati.',
  'Kesuksesan adalah tentang ketekunan.',
  'Jangan menunggu kesempatan, ciptakanlah.',
  'Hidup adalah tentang memberi, bukan menerima.',
  'yok semangattt',
  'Jangan biarkan kegagalan menghentikanmu.',
  'Kebahagiaan ada dalam hal-hal kecil.',
  'Jadilah pribadi yang penuh kasih sayang.',
  'Kesuksesan adalah hasil dari konsistensi.',
  'Jangan menunggu sempurna, mulailah sekarang.',
  'Hidup adalah tentang memberi makna.',
  'Jangan biarkan orang lain mendefinisikanmu.',
  'Kebaikan adalah bahasa universal.',
  'Jadilah pribadi yang selalu optimis.',
  'Kesuksesan adalah tentang proses, bukan hasil.',
  'Jangan takut bermimpi besar.',
  'Hidup adalah tentang menciptakan kenangan.',
  'Jangan biarkan rasa takut mengendalikanmu.',
  'Kebahagiaan adalah ketika kita bersyukur.',
  'Capekk cok wkwk',
  'Jadilah pribadi yang selalu rendah hati.',
  'Kesuksesan adalah tentang ketekunan.',
  'Jangan menunggu kesempatan, ciptakanlah.',
  'Hidup adalah tentang memberi, bukan menerima.',
  'Jangan biarkan kegagalan menghentikanmu.',
  'Kebahagiaan ada dalam hal-hal kecil.',
  'Jadilah pribadi yang penuh kasih sayang.',
  'Kesuksesan adalah hasil dari konsistensi.',
  'Jangan menunggu sempurna, mulailah sekarang.',
  'Hidup adalah tentang memberi makna.',
  'Jangan biarkan orang lain mendefinisikanmu.',
  'Kebaikan adalah bahasa universal.',
  'Jadilah pribadi yang selalu optimis.',
  'Kesuksesan adalah tentang proses, bukan hasil.',
  'gas lagi kata-kata bijak wokwokwok',
  'Jangan takut bermimpi besar.',
  'Hidup adalah tentang menciptakan kenangan.',
  'Jangan biarkan rasa takut mengendalikanmu.',
  'Kebahagiaan adalah ketika kita bersyukur.',
  'Jadilah pribadi yang selalu rendah hati.',
  'Kesuksesan adalah tentang ketekunan.',
  'Jangan menunggu kesempatan, ciptakanlah.',
  'Hidup adalah tentang memberi, bukan menerima.',
  'Jangan biarkan kegagalan menghentikanmu.',
  'Kebahagiaan ada dalam hal-hal kecil.',
  'Jadilah pribadi yang penuh kasih sayang.',
  'Kesuksesan adalah hasil dari konsistensi.',
  'Jangan menunggu sempurna, mulailah sekarang.',
  'Hidup adalah tentang memberi makna.',
  'pahhaammm',
  'Jangan biarkan orang lain mendefinisikanmu.',
  'Kebaikan adalah bahasa universal.',
  'Jadilah pribadi yang selalu optimis.',
  'Kesuksesan adalah tentang proses, bukan hasil.',
  'Jangan takut bermimpi besar.',
  'Hidup adalah tentang menciptakan kenangan.',
  'Jangan biarkan rasa takut mengendalikanmu.',
  'Kebahagiaan adalah ketika kita bersyukur.',
  'Jadilah pribadi yang selalu rendah hati.',
  'Kesuksesan adalah tentang ketekunan.',
  'Jangan menunggu kesempatan, ciptakanlah.',
  'Hidup adalah tentang memberi, bukan menerima.',
  'Jangan biarkan kegagalan menghentikanmu.',
  'Kebahagiaan ada dalam hal-hal kecil.',
  'gas lagi kata-kata bijaknya',
  'Jadilah pribadi yang penuh kasih sayang.',
  'Kesuksesan adalah hasil dari konsistensi.',
  'Jangan menunggu sempurna, mulailah sekarang.',
  'Hidup adalah tentang memberi makna.',
  'Jangan biarkan orang lain mendefinisikanmu.',
  'Kebaikan adalah bahasa universal.',
  'Jadilah pribadi yang selalu optimis.',
  'Kesuksesan adalah tentang proses, bukan hasil.',
  'Jangan takut bermimpi besar.',
  'Hidup adalah tentang menciptakan kenangan.',
  'Jangan biarkan rasa takut mengendalikanmu.',
  'Kebahagiaan adalah ketika kita bersyukur.',
  'Jadilah pribadi yang selalu rendah hati.',
  'Kesuksesan adalah tentang ketekunan.',
  'Jangan menunggu kesempatan, ciptakanlah.',
  'Hidup adalah tentang memberi, bukan menerima.',
  'Jangan biarkan kegagalan menghentikanmu.',
  'Kebahagiaan ada dalam hal-hal kecil.',
  'Jadilah pribadi yang penuh kasih sayang.',
  'Kesuksesan adalah hasil dari konsistensi.',
  'Jangan menunggu sempurna, mulailah sekarang.',
  'Hidup adalah tentang memberi makna.',
  'Jangan biarkan orang lain mendefinisikanmu.',
  'Kebaikan adalah bahasa universal.',
  'Cukup saya sudah muakk',
  'Jadilah pribadi yang selalu optimis.',
  'Kesuksesan adalah tentang proses, bukan hasil.',
  'Jangan takut bermimpi besar.',
  'Hidup adalah tentang menciptakan kenangan.',
  'Jangan biarkan rasa takut mengendalikanmu.',
  'Kebahagiaan adalah ketika kita bersyukur.',
  'Jadilah pribadi yang selalu rendah hati.',
  'Kesuksesan adalah tentang ketekunan.',
  'Jangan menunggu kesempatan, ciptakanlah.',
  'Hidup adalah tentang memberi, bukan menerima.',
  'Jangan biarkan kegagalan menghentikanmu.',
  'Kebahagiaan ada dalam hal-hal kecil.',
  'Jadilah pribadi yang penuh kasih sayang.',
  'Kesuksesan adalah hasil dari konsistensi.',
  'push terus sampai mabok',
  'Jangan menunggu sempurna, mulailah sekarang.',
  'Hidup adalah tentang memberi makna.',
  'Jangan biarkan orang lain mendefinisikanmu.',
  'Kebaikan adalah bahasa universal.',
  'Jadilah pribadi yang selalu optimis.',
  'Kesuksesan adalah tentang proses, bukan hasil.',
  'Jangan takut bermimpi besar.',
  'Hidup adalah tentang menciptakan kenangan.',
  'Jangan biarkan rasa takut mengendalikanmu.',
  'Kebahagiaan adalah ketika kita bersyukur.',
  'Jadilah pribadi yang selalu rendah hati.',
  'Kesuksesan adalah tentang ketekunan.',
  'Jangan menunggu kesempatan, ciptakanlah.',
  'Hidup adalah tentang memberi, bukan menerima.',
  'Tetap semangat bg',
  'Jangan biarkan kegagalan menghentikanmu.',
  'Kebahagiaan ada dalam hal-hal kecil.',
  'Jadilah pribadi yang penuh kasih sayang.',
  'Kesuksesan adalah hasil dari konsistensi.',
  'Jangan menunggu sempurna, mulailah sekarang.',
  'Hidup adalah tentang memberi makna.',
  'Jangan biarkan orang lain mendefinisikanmu.',
  'Kebaikan adalah bahasa universal.',
  'Jadilah pribadi yang selalu optimis.',
  'Kesuksesan adalah tentang proses, bukan hasil.',
  'Jangan takut bermimpi besar.',
  'Hidup adalah tentang menciptakan kenangan.',
  'Jangan biarkan rasa takut mengendalikanmu.',
  'Kebahagiaan adalah ketika kita bersyukur.',
  'cukup sudahhh muakk',
  'Jadilah pribadi yang selalu rendah hati.',
  'Kesuksesan adalah tentang ketekunan.',
  'Jangan menunggu kesempatan, ciptakanlah.',
  'Hidup adalah tentang memberi, bukan menerima.',
  'Jangan biarkan kegagalan menghentikanmu.',
  'Kebahagiaan ada dalam hal-hal kecil.',
  'Jadilah pribadi yang penuh kasih sayang.',
  'Kesuksesan adalah hasil dari konsistensi.',
  'Jangan menunggu sempurna, mulailah sekarang.',
  'Hidup adalah tentang memberi makna.',
  'Jangan biarkan orang lain mendefinisikanmu.',
  'Kebaikan adalah bahasa universal.',
  'Jadilah pribadi yang selalu optimis.',
  'Kesuksesan adalah tentang proses, bukan hasil.',
  'mabok kata-kata bijak wokwokwok',
  'Jangan takut bermimpi besar.',
  'Hidup adalah tentang menciptakan kenangan.',
  'Jangan biarkan rasa takut mengendalikanmu.',
  'Kebahagiaan adalah ketika kita bersyukur.',
  'Jadilah pribadi yang selalu rendah hati.',
  'Kesuksesan adalah tentang ketekunan.',
  'Jangan menunggu kesempatan, ciptakanlah.',
  'Hidup adalah tentang memberi, bukan menerima.',
  'Jangan biarkan kegagalan menghentikanmu.',
  'Kebahagiaan ada dalam hal-hal kecil.',
  'Jadilah pribadi yang penuh kasih sayang.',
  'Kesuksesan adalah hasil dari konsistensi.',
  'Jangan menunggu sempurna, mulailah sekarang.',
  'Hidup adalah tentang memberi makna.',
  'gas lagi kata-bijak wokwokwok',
  'Jangan biarkan orang lain mendefinisikanmu.',
  'Kebaikan adalah bahasa universal.',
  'Jadilah pribadi yang selalu optimis.',
  'Kesuksesan adalah tentang proses, bukan hasil.',
  'Jangan takut bermimpi besar.',
  'Hidup adalah tentang menciptakan kenangan.',
  'Jangan biarkan rasa takut mengendalikanmu.',
  'Kebahagiaan adalah ketika kita bersyukur.',
  'Jadilah pribadi yang selalu rendah hati.',
  'Kesuksesan adalah tentang ketekunan.',
  'Jangan menunggu kesempatan, ciptakanlah.',
];

// Fungsi untuk mengetik, menekan Enter, lalu menghapus
function sendMessage() {
  let index = 0;

  setInterval(() => {
    const msg = messages[index];

    robot.typeString(msg); // Mengetik teks
    robot.keyTap('enter'); // Tekan Enter

    console.log(`Terkirim: ${msg}`);

    // Tunggu sebentar sebelum menghapus
    setTimeout(() => {
      // Tekan Backspace beberapa kali untuk menghapus pesan
      for (let i = 0; i < msg.length; i++) {
        robot.keyTap('backspace');
      }

      console.log(`Dihapus: ${msg}`);
    }, 1000); // Tunggu 1 detik sebelum menghapus

    // Lanjut ke pesan berikutnya
    index = (index + 1) % messages.length; // Loop kembali ke awal setelah akhir array
  }, 10000); // Interval 10 detik per siklus
}

// Jalankan script
sendMessage();
